export const seedUsers = [
  {
    name: "Admin User",
    email: "admin@nestfinder.com",
    password: "admin123",
    role: "admin",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    name: "Sarah Johnson",
    email: "user@nestfinder.com",
    password: "user123",
    role: "user",
    avatar: "https://i.pravatar.cc/150?img=5",
  },
];

export const seedItems = [
  {
    title: "Luxury Penthouse in Manhattan",
    shortDescription:
      "Stunning penthouse with panoramic city views and modern amenities.",
    fullDescription:
      "Experience luxury living in this beautifully designed penthouse apartment in the heart of Manhattan. Floor-to-ceiling windows offer breathtaking views of the city skyline. The open-concept living space features hardwood floors, a gourmet kitchen with top-of-the-line appliances, and a spacious master bedroom with an en-suite bathroom. Building amenities include a 24-hour doorman, fitness center, and rooftop terrace.",
    price: 450,
    category: "Apartment",
    location: "New York",
    address: "350 Fifth Avenue, New York, NY 10118",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
    ],
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    amenities: [
      "WiFi",
      "Air Conditioning",
      "Kitchen",
      "Doorman",
      "Gym",
      "Rooftop Access",
    ],
    featured: true,
  },
  {
    title: "Beachfront Villa in Malibu",
    shortDescription:
      "Wake up to ocean waves in this stunning Malibu beachfront villa.",
    fullDescription:
      "This spectacular beachfront villa offers direct access to Malibu's pristine beaches. The property features an open-plan living area with ocean views, a fully equipped chef's kitchen, and multiple bedrooms each with en-suite bathrooms. The outdoor space includes a private pool, hot tub, and lounging areas perfect for watching the sunset over the Pacific.",
    price: 1200,
    category: "Villa",
    location: "Los Angeles",
    address: "21500 Pacific Coast Hwy, Malibu, CA 90265",
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    ],
    bedrooms: 5,
    bathrooms: 4,
    guests: 10,
    amenities: [
      "WiFi",
      "Pool",
      "Beach Access",
      "Hot Tub",
      "BBQ Grill",
      "Parking",
      "Ocean View",
    ],
    featured: true,
  },
  {
    title: "Cozy Mountain Cabin in Aspen",
    shortDescription:
      "Rustic charm meets modern comfort in this mountain retreat.",
    fullDescription:
      "Escape to this beautiful mountain cabin nestled among the aspen trees. The cabin features a warm and inviting interior with exposed wooden beams, a stone fireplace, and large windows framing mountain views. Perfect for ski trips or summer hiking adventures, this property offers the ideal mountain getaway experience.",
    price: 350,
    category: "Cabin",
    location: "Denver",
    address: "123 Mountain Road, Aspen, CO 81611",
    images: [
      "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800",
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800",
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800",
    ],
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    amenities: [
      "WiFi",
      "Fireplace",
      "Hot Tub",
      "Ski Storage",
      "Mountain View",
      "Parking",
    ],
    featured: true,
  },
  {
    title: "Modern Loft in Downtown Chicago",
    shortDescription:
      "Industrial-chic loft in the vibrant heart of Chicago.",
    fullDescription:
      "This stunning converted warehouse loft features soaring ceilings, original exposed brick walls, and massive industrial windows flooding the space with natural light. The open floor plan is perfect for entertaining, with a modern kitchen, comfortable living area, and a cozy sleeping loft. Located in the trendy Fulton Market district, you're steps away from world-class restaurants and nightlife.",
    price: 275,
    category: "Loft",
    location: "Chicago",
    address: "456 N Green St, Chicago, IL 60642",
    images: [
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
    ],
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    amenities: ["WiFi", "Air Conditioning", "Kitchen", "Gym", "Doorman"],
    featured: false,
  },
  {
    title: "Oceanview Condo in South Beach",
    shortDescription:
      "Stunning ocean views from this premium South Beach condo.",
    fullDescription:
      "Enjoy the ultimate Miami lifestyle in this beautifully appointed oceanfront condo. Wake up to stunning views of the Atlantic Ocean and step out onto your private balcony to feel the ocean breeze. The condo features modern furnishings, a fully equipped kitchen, and access to world-class building amenities including multiple pools, spa, and private beach access.",
    price: 380,
    category: "Condo",
    location: "Miami",
    address: "1000 S Pointe Dr, Miami Beach, FL 33139",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
    ],
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    amenities: [
      "WiFi",
      "Pool",
      "Beach Access",
      "Spa",
      "Parking",
      "Ocean View",
      "Balcony",
    ],
    featured: true,
  },
  {
    title: "Victorian Townhouse in Pacific Heights",
    shortDescription:
      "Elegant Victorian architecture with modern updates throughout.",
    fullDescription:
      "This meticulously restored Victorian townhouse combines historic charm with contemporary luxury. Original details including crown molding, bay windows, and hardwood floors are complemented by modern amenities and tasteful updates. Multiple levels provide generous living space, and the private garden offers a peaceful retreat in the city.",
    price: 520,
    category: "Townhouse",
    location: "San Francisco",
    address: "2780 Pacific Ave, San Francisco, CA 94115",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800",
    ],
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    amenities: [
      "WiFi",
      "Garden",
      "Garage",
      "Fireplace",
      "Washer/Dryer",
      "Kitchen",
    ],
    featured: false,
  },
  {
    title: "Charming Studio in Austin's Rainey Street",
    shortDescription:
      "Hip downtown studio steps from the best bars and restaurants.",
    fullDescription:
      "This stylish studio apartment puts you in the heart of Austin's famous Rainey Street district. The thoughtfully designed space maximizes every square foot with clever storage solutions and a modern aesthetic. Enjoy a morning coffee on the Juliet balcony while watching the neighborhood wake up, then explore the dozens of bars, restaurants, and food trucks just steps away.",
    price: 150,
    category: "Studio",
    location: "Austin",
    address: "99 Rainey St, Austin, TX 78701",
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800",
      "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800",
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800",
    ],
    bedrooms: 0,
    bathrooms: 1,
    guests: 2,
    amenities: ["WiFi", "Air Conditioning", "Kitchen", "Balcony", "Pool"],
    featured: false,
  },
  {
    title: "Spacious Family House in Bellevue",
    shortDescription:
      "Perfect family home with large yard in top-rated school district.",
    fullDescription:
      "This beautifully maintained family home offers everything you need for comfortable suburban living. The main level features an open-concept kitchen, dining, and living area perfect for family gatherings. Four generous bedrooms upstairs include a primary suite with walk-in closet and spa-like bathroom. The fully fenced backyard with mature trees is ideal for kids and pets.",
    price: 420,
    category: "House",
    location: "Seattle",
    address: "12456 NE 20th St, Bellevue, WA 98004",
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    ],
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    amenities: [
      "WiFi",
      "Garage",
      "Backyard",
      "Washer/Dryer",
      "Kitchen",
      "Fireplace",
      "Air Conditioning",
    ],
    featured: true,
  },
  {
    title: "Art Deco Apartment in South Beach",
    shortDescription:
      "Stylish Art Deco gem in the heart of Miami's cultural district.",
    fullDescription:
      "Step back in time in this beautifully preserved Art Deco apartment featuring original terrazzo floors, chrome fixtures, and pastel color palette. Recently updated with modern appliances while maintaining its historic character. The building's iconic facade and prime location make this a truly unique living experience.",
    price: 220,
    category: "Apartment",
    location: "Miami",
    address: "1100 Collins Ave, Miami Beach, FL 33139",
    images: [
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800",
    ],
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    amenities: [
      "WiFi",
      "Pool",
      "Air Conditioning",
      "Kitchen",
      "Beach Access",
    ],
    featured: false,
  },
  {
    title: "Rustic Farmhouse in Hill Country",
    shortDescription:
      "Peaceful Hill Country retreat on 5 acres of rolling hills.",
    fullDescription:
      "This charming farmhouse sits on five acres of beautiful Texas Hill Country. The property features a renovated farmhouse with wraparound porch, a separate guest cottage, and stunning views of the surrounding landscape. Perfect for those seeking tranquility while still being just 30 minutes from downtown Austin.",
    price: 300,
    category: "House",
    location: "Austin",
    address: "4500 FM 2244, Austin, TX 78738",
    images: [
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800",
      "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=800",
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800",
    ],
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    amenities: [
      "WiFi",
      "Pool",
      "Fire Pit",
      "BBQ Grill",
      "Hill View",
      "Parking",
      "Porch",
    ],
    featured: true,
  },
  {
    title: "Sleek Downtown Condo in River North",
    shortDescription:
      "Contemporary luxury in Chicago's most exciting neighborhood.",
    fullDescription:
      "This sophisticated high-rise condo offers panoramic views of the Chicago River and skyline. Floor-to-ceiling windows, premium finishes, and an open layout create a luxurious urban retreat. The building features resort-style amenities including an indoor pool, sky terrace, and state-of-the-art fitness center.",
    price: 310,
    category: "Condo",
    location: "Chicago",
    address: "333 N Clark St, Chicago, IL 60654",
    images: [
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
    ],
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    amenities: [
      "WiFi",
      "Pool",
      "Gym",
      "Doorman",
      "Parking",
      "River View",
      "Balcony",
    ],
    featured: false,
  },
  {
    title: "Seaside Cottage in Cape Cod",
    shortDescription:
      "Classic New England cottage with private beach access.",
    fullDescription:
      "This quintessential Cape Cod cottage offers the perfect blend of coastal charm and modern comfort. Shingle-style architecture, a screened porch, and a beautifully landscaped yard create an inviting atmosphere. The private path leads directly to a secluded beach, ideal for morning walks and sunset watching.",
    price: 275,
    category: "Cabin",
    location: "New York",
    address: "89 Shore Rd, Chatham, MA 02633",
    images: [
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800",
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800",
      "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800",
    ],
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    amenities: [
      "WiFi",
      "Beach Access",
      "Porch",
      "BBQ Grill",
      "Garden",
      "Fireplace",
    ],
    featured: false,
  },
];
